import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import {ReduxProvider} from "@/component/ReduxProvider";
import {Vazirmatn} from "next/font/google";
import {Toaster} from "react-hot-toast";

export const metadata: Metadata = {
    title: "فروشگاه کفش",
    description: "Generated by create next app",
};

const vazir = Vazirmatn({
    subsets: ["arabic"],
    weight: ["300", "400", "600", "700", "800", "900"],
    variable: "--font-vazir",
});

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="fa" dir="rtl" suppressHydrationWarning>
        <head>
            <script
                dangerouslySetInnerHTML={{
                    __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  if (theme === 'dark' || !theme) {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })();
            `,
                }}
            />
        </head>
        <body
            className={`${vazir.className} bg-background text-text transition-colors duration-300`}
        >
        <ReduxProvider>
            <Toaster position="top-center" reverseOrder={false}/>
            {children}
        </ReduxProvider>
        </body>
        </html>
    );
}