import type {Metadata} from "next";
import React from "react";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <div className="min-h-screen flex flex-col items-center justify-center p-4 bg-background">
            <div className="w-full max-w-sm bg-background-secondary p-6 rounded-lg">
                <Link href="/">
                    <Image
                        src="/logo.png"
                        width={120}
                        height={120}
                        alt="logo"
                        className="mx-auto"
                        priority
                    />
                </Link>
                {children}
            </div>
        </div>
    );
}
